# Generated by Django 6.0.2 on 2026-02-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='payment_method',
            field=models.CharField(choices=[('BKASH', 'বিকাশ'), ('NAGAD', 'নগদ'), ('ROCKET', 'রকেট'), ('BANK', 'ব্যাংক')], max_length=100),
        ),
    ]
