# Generated by Django 6.0.2 on 2026-02-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sellerprofile_is_active_sellerprofile_total_products_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='nid_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BKASH', 'বিকাশ'), ('NAGAD', 'নগদ'), ('ROCKET', 'রকেট'), ('BANK', 'ব্যাংক')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='payment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='store_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('ADMIN', 'Admin')], default='ADMIN', max_length=10),
        ),
    ]
