# Generated by Django 6.0.2 on 2026-02-24 04:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_productimage_productreview_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('BKASH', '📱 বিকাশ'), ('NAGAD', '📱 নগদ'), ('ROCKET', '🚀 রকেট'), ('CARD', '💳 কার্ড'), ('CASH', '💰 ক্যাশ অন ডেলিভারি')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '⏳ পেন্ডিং'), ('PAID', '💵 পেইড'), ('FAILED', '❌ ফেইলড'), ('REFUNDED', '💰 রিফান্ডেড')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '📝 পেন্ডিং'), ('CONFIRMED', '✅ কনফার্মড'), ('PROCESSING', '⚙️ প্রসেসিং'), ('SHIPPED', '🚚 শিপড'), ('DELIVERED', '📦 ডেলিভারড'), ('CANCELLED', '❌ ক্যান্সেলড'), ('RETURNED', '🔄 রিটার্নড')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='product_price',
        ),
        migrations.AddField(
            model_name='order',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Dhaka', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='ক্রেতার বিশেষ অনুরোধ'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='অ্যাডমিনের জন্য নোট'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='TEMP-ORDER', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BKASH', '📱 বিকাশ'), ('NAGAD', '📱 নগদ'), ('ROCKET', '🚀 রকেট'), ('CARD', '💳 কার্ড'), ('CASH', '💰 ক্যাশ অন ডেলিভারি')], default='CASH', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', '⏳ পেন্ডিং'), ('PAID', '💵 পেইড'), ('FAILED', '❌ ফেইলড'), ('REFUNDED', '💰 রিফান্ডেড')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 24, 4, 46, 44, 717028, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', '📝 পেন্ডিং'), ('CONFIRMED', '✅ কনফার্মড'), ('PROCESSING', '⚙️ প্রসেসিং'), ('SHIPPED', '🚚 শিপড'), ('DELIVERED', '📦 ডেলিভারড'), ('CANCELLED', '❌ ক্যান্সেলড'), ('RETURNED', '🔄 রিটার্নড')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order'),
        ),
    ]
